apiVersion: v1
kind: Service
metadata:
  name: go-app-deployment
spec:
  selector:
    app.kubernetes.io/name: MyApp
  type: Nodeport
  ports:
    - protocol: TCP
      port: Nodeport
      targetPort: 8080
      Nodeport: 30009